const app=document.querySelector("#app");const installBtn=document.querySelector("#installBtn");let deferredPrompt=null;
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});
installBtn.addEventListener("click",async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.hidden=true});
const demoChildren=[
{name:"Ana (demo)",age:"5 anos",goal:"Linguagem e nomeação",progress:2},
{name:"Pedro (demo)",age:"7 anos",goal:"Consciência fonológica",progress:1}
];
const activities=[
{title:"Diga o nome",area:"Linguagem",icon:"🐸",goal:"Nomeação",desc:"Apresentar uma figura e incentivar a criança a tentar nomeá-la."},
{title:"Rimas",area:"Consciência fonológica",icon:"🎵",goal:"Percepção de rimas",desc:"Explorar palavras que terminam com sons semelhantes."},
{title:"Turnos de conversa",area:"Comunicação",icon:"💬",goal:"Participação comunicativa",desc:"Alternar fala e escuta durante uma brincadeira."}
];
const screens={
child:{title:"Minha Jornada",intro:"Atividades demonstrativas simples, sempre com orientação adequada.",body:()=>`<div class="card"><strong>Atividade de hoje</strong><div class="activity"><div class="activity-icon">🐸</div><div><strong>Diga o nome</strong><p>Mostre a imagem e incentive a criança a dizer “sapo”. Aceite tentativas e valorize a comunicação.</p><small>Objetivo: nomeação e participação.</small></div></div><button class="primary" data-done>Concluir demonstração</button></div><div class="card"><strong>Meu progresso</strong><p>Atividades realizadas: <b id="count">0</b></p></div>`},
family:{title:"Área da Família",intro:"A família pode apoiar a prática com orientações simples.",body:()=>`<div class="card"><strong>Orientação de hoje</strong><p>Reserve alguns minutos em um ambiente tranquilo. Converse, brinque e dê tempo para a criança responder.</p><button class="primary" data-done>Marcar demonstração como realizada</button></div><div class="card"><strong>Observações</strong><textarea id="obs" placeholder="Ex.: participou bem da brincadeira..." rows="4"></textarea><button class="secondary" data-save>Salvar observação local</button></div>`},
professional:{title:"Área do Profissional",intro:"Painel demonstrativo para organizar acompanhamento.",body:()=>`<div class="stats"><div><b>2</b><small>Crianças demo</small></div><div><b>3</b><small>Atividades</small></div><div><b>0</b><small>Dados reais</small></div></div><h2>Crianças demonstrativas</h2>${demoChildren.map((c,i)=>`<div class="card patient"><div><strong>${c.name}</strong><small>${c.age} · Meta: ${c.goal}</small></div><button class="secondary" data-patient="${i}">Abrir</button></div>`).join("")}<div id="patientDetail"></div><div class="card"><strong>Princípio clínico</strong><p>O profissional avalia, define objetivos e decide como utilizar cada atividade. A ferramenta não substitui avaliação ou atendimento.</p></div>`},
library:{title:"Biblioteca científica",intro:"Cada atividade deve ter objetivo, público, referência, responsável e data de revisão.",body:()=>activities.map(a=>`<div class="card activity"><div class="activity-icon">${a.icon}</div><div><strong>${a.title}</strong><small>${a.area} · Objetivo: ${a.goal}</small><p>${a.desc}</p><span class="tag">Revisão profissional necessária</span></div></div>`).join("")+`<div class="card"><strong>Referências</strong><p>As referências científicas serão vinculadas individualmente a cada conteúdo antes de uso assistencial.</p></div>`}
};
function bindScreen(){const homeBtn=document.querySelector("[data-home]");if(homeBtn)homeBtn.onclick=home;const done=document.querySelector("[data-done"]);if(done)done.onclick=()=>{done.textContent="✓ Registrado nesta demonstração";done.disabled=true;const n=document.querySelector("#count");if(n)n.textContent="1"};const save=document.querySelector("[data-save]");if(save)save.onclick=()=>{localStorage.setItem("fonoapoio-demo-obs",document.querySelector("#obs").value);save.textContent="✓ Salvo neste dispositivo"};document.querySelectorAll("[data-patient]").forEach(b=>b.onclick=()=>{const c=demoChildren[Number(b.dataset.patient)];document.querySelector("#patientDetail").innerHTML=`<div class="card"><strong>${c.name}</strong><p><b>Idade:</b> ${c.age}<br><b>Meta demonstrativa:</b> ${c.goal}</p><button class="secondary" data-close>Fechar</button></div>`;document.querySelector("[data-close]").onclick=()=>document.querySelector("#patientDetail").innerHTML=""})}
function showRole(role){const s=screens[role];app.innerHTML=`<section class="screen"><button class="back" data-home>← Voltar</button><h1>${s.title}</h1><p>${s.intro}</p>${s.body()}</section>`;bindScreen()}
function home(){location.reload()}
document.querySelectorAll("[data-role]").forEach(b=>b.addEventListener("click",()=>showRole(b.dataset.role)));
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.warn));