const app=document.querySelector("#app");const installBtn=document.querySelector("#installBtn");let deferredPrompt=null;
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});
installBtn.addEventListener("click",async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.hidden=true});
const screens={
child:{title:"Minha Jornada",intro:"Vamos praticar uma atividade de comunicação.",body:`<div class="card activity"><div class="activity-icon">🐸</div><div><strong>Diga o nome</strong><p>Mostre a imagem e incentive a criança a dizer “sapo”. Aceite tentativas e valorize a comunicação.</p><small>Objetivo: estimular participação e nomeação.</small></div></div><button class="primary" data-done>Concluir atividade</button>`},
family:{title:"Área da Família",intro:"A família participa do cuidado com orientações simples.",body:`<div class="card"><strong>Atividade de hoje</strong><p>Separe alguns minutos em um ambiente tranquilo. Converse, brinque e dê tempo para a criança responder.</p><button class="primary" data-done>Marcar como realizada</button></div><div class="card"><strong>Observação</strong><p>Registre para o profissional o que foi fácil, difícil ou diferente hoje.</p></div>`},
professional:{title:"Área do Profissional",intro:"Espaço inicial para organizar o acompanhamento.",body:`<div class="card"><strong>Próximos módulos</strong><p>Cadastro de pacientes, metas individuais, seleção de atividades, registros de evolução e histórico. Nesta primeira versão não usamos dados reais.</p></div><div class="card"><strong>Princípio clínico</strong><p>O profissional avalia, define objetivos e decide como utilizar cada atividade.</p></div>`},
library:{title:"Biblioteca científica",intro:"Atividades devem ter objetivo, público, referência e revisão.",body:`<div class="card"><strong>Modelo de atividade</strong><p><b>Objetivo:</b> nomeação e linguagem.<br><b>Faixa etária:</b> definida após revisão profissional.<br><b>Referência:</b> será registrada junto à atividade.<br><b>Revisão:</b> cada conteúdo deverá ter responsável e data de revisão.</p></div><div class="card"><strong>Nota científica</strong><p>Conteúdo clínico será desenvolvido e revisado com base em evidências e referências profissionais reconhecidas.</p></div>`}
};
function showRole(role){const s=screens[role];app.innerHTML=`<section class="screen"><button class="back" data-home>← Voltar</button><h1>${s.title}</h1><p>${s.intro}</p>${s.body}</section>`;document.querySelector("[data-home]").onclick=home;const done=document.querySelector("[data-done]");if(done)done.onclick=()=>{done.textContent="✓ Registrado nesta demonstração";done.disabled=true}}
function home(){location.reload()}
document.querySelectorAll("[data-role]").forEach(b=>b.addEventListener("click",()=>showRole(b.dataset.role)));
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.warn));