const app=document.querySelector("#app");
const installBtn=document.querySelector("#installBtn");
let deferredPrompt=null;
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});
installBtn.addEventListener("click",async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.hidden=true});
const activities=[{title:"Diga o nome",area:"Linguagem",icon:"🐸",goal:"Nomeação"},{title:"Rimas",area:"Consciência fonológica",icon:"🎵",goal:"Percepção de rimas"},{title:"Turnos de conversa",area:"Comunicação",icon:"💬",goal:"Participação comunicativa"}];
const children=[{name:"Ana (demo)",age:"5 anos",goal:"Linguagem e nomeação",assigned:["Diga o nome","Turnos de conversa"]},{name:"Pedro (demo)",age:"7 anos",goal:"Consciência fonológica",assigned:["Rimas"]}];
function childScreen(){return "<section class=\"screen\"><button class=\"back\" data-home>← Voltar</button><h1>Minha Jornada</h1><p>Olá! Hoje temos uma atividade preparada pela sua fono.</p><div class=\"child-welcome\"><span>🌟</span><div><strong>Vamos brincar?</strong><p>Faça com calma. Tente, escute e divirta-se!</p></div></div><h2>Atividade de hoje</h2><div class=\"activity-big\"><div class=\"big-icon\">🐸</div><div><span class=\"tag\">Linguagem</span><h2>Diga o nome</h2><p>Olhe a figura. Você consegue dizer o nome dela?</p><button class=\"primary\" data-done>Consegui!</button></div></div><div class=\"card\"><strong>⭐ Minha jornada</strong><p>Atividades concluídas hoje: <b id=\"count\">0</b></p><div class=\"progress\"><span id=\"progressBar\"></span></div></div></section>"}
function professionalScreen(){let list=children.map((c,i)=>"<div class=\"card patient\"><div class=\"patient-avatar\">🧒</div><div class=\"patient-info\"><strong>"+c.name+"</strong><small>"+c.age+" · Meta: "+c.goal+"</small></div><button class=\"secondary\" data-patient=\""+i+"\">Acompanhar</button></div>").join("");let acts=activities.map((a)=>"<div><span>"+a.icon+"</span><span><b>"+a.title+"</b><small>"+a.area+" · "+a.goal+"</small></span><button class=\"secondary\" data-activity=\""+a.title+"\">Selecionar</button></div>").join("");return "<section class=\"screen\"><button class=\"back\" data-home>← Voltar</button><h1>Área da Fonoaudióloga</h1><p>Planeje as atividades e acompanhe cada criança.</p><div class=\"stats\"><div><b>2</b><small>Crianças demo</small></div><div><b>3</b><small>Atividades</small></div><div><b>0</b><small>Dados reais</small></div></div><div class=\"section-head\"><h2>Minhas crianças</h2><button class=\"secondary\" data-add>+ Nova</button></div>"+list+"<div id=\"patientDetail\"></div><div class=\"card\"><strong>📚 Biblioteca de atividades</strong><p>Escolha atividades para montar uma jornada personalizada.</p><div class=\"mini-list\">"+acts+"</div></div></section>"}
function bind(){document.querySelector("[data-home]").onclick=home;const done=document.querySelector("[data-done]");if(done)done.onclick=()=>{done.textContent="✓ Muito bem!";done.disabled=true;document.querySelector("#count").textContent="1";document.querySelector("#progressBar").style.width="100%"};const add=document.querySelector("[data-add]");if(add)add.onclick=()=>alert("Nesta demonstração usamos somente crianças fictícias. O cadastro protegido será criado na próxima etapa.");document.querySelectorAll("[data-patient]").forEach(b=>b.onclick=()=>{const c=children[Number(b.dataset.patient)];document.querySelector("#patientDetail").innerHTML="<div class=\"card detail\"><button class=\"back\" data-close>← Fechar</button><h2>"+c.name+"</h2><p><b>"+c.age+"</b> · Objetivo atual: <b>"+c.goal+"</b></p><h3>Jornada atribuída</h3>"+c.assigned.map(x=>"<div class=\"assigned\">✓ "+x+"</div>").join("")+"<button class=\"primary\" data-plan>Editar jornada</button></div>";document.querySelector("[data-close]").onclick=()=>document.querySelector("#patientDetail").innerHTML="";document.querySelector("[data-plan]").onclick=()=>alert("Editor de jornada: selecionar atividades e definir a sequência.")});document.querySelectorAll("[data-activity]").forEach(b=>b.onclick=()=>{b.textContent="✓ Selecionada";b.disabled=true})}
function show(role){app.innerHTML=role==="child"?childScreen():professionalScreen();bind()}
function home(){location.reload()}
document.querySelectorAll("[data-role]").forEach(b=>b.addEventListener("click",()=>show(b.dataset.role)));
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.warn));